export const fakeBooks = [
  {
    author_name: ["J.R.R. Tolkien"],
    cover_edition_key: "OL51694024M",
    first_publish_year: 1954,
    key: "OL27448W",
    title: "The Lord of the Rings",
    editions: {
      numFound: 207,
      start: 0,
      numFoundExact: true,
      docs: [{ key: "/books/OL51711484M", title: "The Lord of the Rings" }],
    },
    cover_url: "https://covers.openlibrary.org/b/olid/OL51694024M-M.jpg",
    subtitle: null,
    author: "J.R.R. Tolkien",
    description: {
      type: "/type/text",
      value:
        "Originally published from 1954 through 1956, J.R.R. Tolkien's richly complex series ushered in a new age of epic adventure storytelling. A philologist and illustrator who took inspiration from his work, Tolkien invented the modern heroic quest novel from the ground up, creating not just a world, but a domain, not just a lexicon, but a language, that would spawn countless imitators and lead to the inception of the epic fantasy genre. Today, THE LORD OF THE RINGS is considered \"the most influential fantasy novel ever written.\" (THE ENCYCLOPEDIA OF FANTASY)\r\n\r\nDuring his travels across Middle-earth, the hobbit Bilbo Baggins had found the Ring. But the simple band of gold was far from ordinary; it was in fact the One Ring - the greatest of the ancient Rings of Power. Sauron, the Dark Lord, had infused it with his own evil magic, and when it was lost, he was forced to flee into hiding.\r\n\r\nBut now Sauron's exile has ended and his power is spreading anew, fueled by the knowledge that his treasure has been found. He has gathered all the Great Rings to him, and will stop at nothing to reclaim the One that will complete his dominion. The only way to stop him is to cast the Ruling Ring deep into the Fire-Mountain at the heart of the land of Mordor--Sauron's dark realm.\r\n\r\nFate has placed the burden in the hands of Frodo Baggins, Bilbo's heir...and he is resolved to bear it to its end. Or his own. \r\n\r\n\r\n----------\r\n\r\n\r\n**Contains**\r\n\r\n - [The Fellowship of the Ring][1]\r\n - [The Two Towers][2]\r\n - [The Return of the King][3]\r\n - [The Lord of the Rings [2/2]](https://openlibrary.org/works/OL27306128W)\r\n - [The Lord of the Rings [1/6]](https://openlibrary.org/works/OL24170898W)\r\n - [The Lord of the Rings [1/9]](https://openlibrary.org/works/OL27305953W)\r\n - [The Lord of the Rings [2/9]](https://openlibrary.org/works/OL27305892W)\r\n - [The Lord of the Rings [3/9]](https://openlibrary.org/works/OL27306048W)\r\n\r\n\r\n\r\n  [1]: https://openlibrary.org/works/OL14933414W/The_Fellowship_of_the_Ring\r\n  [2]: https://openlibrary.org/works/OL27479W/The_Two_Towers\r\n  [3]: https://openlibrary.org/works/OL27516W/The_Return_of_the_King",
    },
    subject_places: [
      "Mordor",
      "Hornburg",
      "Isengard",
      "Cracks of Doom",
      "Fangorn Forest",
      "Middle Earth",
      "Tierra Media",
    ],
    subject_people: [
      "Frodo Baggins",
      "Samwise Gamgee",
      "Meriadoc Brandybuck",
      "Peregrin Took",
      "Gandalf the Grey",
      "Aragorn",
      "Legolas Greenleaf",
      "Gimli",
      "Boromir",
      "Denethor",
      "Faramir",
      "Galadriel",
      "Celeborn",
      "Elrond",
      "Arwen Undómiel",
      "Bilbo Baggins",
      "Théoden",
      "Éomer",
      "Éowyn",
      "Treebeard",
      "Tom Bombadil",
      "King Thranduil",
      "Silvan Elves",
      "Sauron",
      "Elves of Eregion",
      "the Nazgûl",
      "The Witch-king of Angmar",
      "Saruman the White",
      "Gríma Wormtongue",
      "Gollum",
      "Shelob",
      "Durin's Bane",
      "Mouth of Sauron",
    ],
    subject_times: ["The end of the third age"],
    subjects: [
      "The Lord of the Rings",
      "Fiction",
      "Ficción",
      "English Fantasy fiction",
      "Ficción fantástica inglesa",
      "Fantasy fiction",
      "Open Library Staff Picks",
      "Middle Earth (Imaginary place)",
      "Fiction, fantasy, epic",
      "Middle earth (imaginary place), fiction",
      "Baggins, frodo (fictitious character), fiction",
      "Gandalf (fictitious character), fiction",
      "British and irish fiction (fictional works by one author)",
      "English literature",
      "Frodo Baggins (Fictitious character)",
      "Baggins, bilbo (fictitious character), fiction",
      "Fiction, fantasy, general",
      "English language",
      "Fiction, media tie-in",
      "Gift books",
      "Quests (Expeditions)",
      "Wizards",
      "Terre du Milieu (Lieu imaginaire)",
      "Romans, nouvelles",
      "Quête",
      "Lord of the rings (Tolkien, J.R.R.)",
      "Филологические науки. Художественная литература -- Великобритания -- Английская литература -- с 1945 г. -- Произведения художественной литературы -- Художественная проза -- Романы. Повести. Рассказы -- Фантастические и мистические романы, повести, рассказы. Романы ужасов",
      "Baggins, frodo",
      "Middle earth (imaginary place)--fiction",
      "Fantasy fiction, english",
      "Pr6039.o32 l6 2005",
      "823/.912",
      "Fiction in English",
      "Hobbits (Fictitious characters)",
      "Hobbits (Personnages fictifs)",
    ],
    publish_date: "2003",
    publishers: ["Houghton Mifflin Company"],
    number_of_pages: null,
    isbn_10: ["0618343997"],
    isbn_13: null,
    languages: [{ key: "/languages/eng" }],
    physical_dimensions: null,
    ratings: {
      summary: {
        average: 4.517241379310345,
        count: 87,
        sortable: 4.252337405386547,
      },
      counts: { "1": 3, "2": 2, "3": 7, "4": 10, "5": 65 },
    },
    edition_key: "OL51711484M",
    cover_urls: [
      "https://covers.openlibrary.org/b/olid/OL51694024M-M.jpg",
      "https://covers.openlibrary.org/b/olid/OL51711484M-M.jpg",
    ],
    status: "read",
    review: "good",
    colors: { primary: "#F7BF8F", secondary: "#DA7A66" },
    spines: [
      {
        cacheKey: "OL27448W-spine-placeholder",
        selected: false,
        originalImageHeight: 200,
        originalImageWidth: 60,
      },
      {
        cacheKey: "OL27448W-spine-1744545976188",
        selected: true,
        originalImageHeight: 1702,
        originalImageWidth: 246,
      },
    ],
  },
  {
    author_name: ["James Clear"],
    cover_edition_key: "OL36647151M",
    first_publish_year: 2016,
    key: "OL17930368W",
    title: "Atomic Habits",
    editions: {
      numFound: 41,
      start: 0,
      numFoundExact: true,
      docs: [
        { key: "/books/OL36939272M", title: "Atomic Habits Journal Tracking" },
      ],
    },
    cover_url: "https://covers.openlibrary.org/b/olid/OL36647151M-M.jpg",
    subtitle: null,
    author: "James Clear",
    description: {
      type: "/type/text",
      value:
        "No matter your goals, Atomic Habits offers a proven framework for improving every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
    },
    subject_places: null,
    subject_people: null,
    subject_times: null,
    subjects: [
      "Habit",
      "Habit breaking",
      "Behavior modification",
      "Self-actualization (psychology)",
      "Business",
      "psychology",
      "Personal Growth",
      "New York Times bestseller",
      "BUSINESS & ECONOMICS / Organizational Behavior",
      "PSYCHOLOGY / Social Psychology",
      "SELF-HELP / Personal Growth / General.",
      "Self-help / personal growth / general",
    ],
    publish_date: "2020",
    publishers: ["Independently Published"],
    number_of_pages: null,
    isbn_10: null,
    isbn_13: ["9798613461172"],
    languages: [{ key: "/languages/eng" }],
    physical_dimensions: null,
    ratings: {
      summary: {
        average: 4.043269230769231,
        count: 1040,
        sortable: 3.964044250128235,
      },
      counts: { "1": 152, "2": 31, "3": 72, "4": 150, "5": 635 },
    },
    edition_key: "OL36939272M",
    cover_urls: [
      "https://covers.openlibrary.org/b/olid/OL36647151M-M.jpg",
      "https://covers.openlibrary.org/b/olid/OL36939272M-M.jpg",
    ],
    status: "read",
    review: "good",
    colors: { primary: "#27231F", secondary: "#8E7860" },
    spines: [
      {
        cacheKey: "OL17930368W-spine-placeholder",
        selected: false,
        originalImageHeight: 200,
        originalImageWidth: 60,
      },
      {
        cacheKey: "OL17930368W-spine-1744549302696",
        selected: true,
        originalImageHeight: 785,
        originalImageWidth: 74,
      },
    ],
  },
  {
    author_name: ["Robert Greene", "Joost Elffers"],
    cover_edition_key: "OL24274306M",
    first_publish_year: 1998,
    key: "OL1968368W",
    title: "The 48 Laws of Power",
    editions: {
      numFound: 32,
      start: 0,
      numFoundExact: true,
      docs: [{ key: "/books/OL25418275M", title: "The 48 laws of power" }],
    },
    cover_url: "https://covers.openlibrary.org/b/olid/OL24274306M-M.jpg",
    subtitle: null,
    author: "Robert Greene",
    description: {
      type: "/type/text",
      value:
        'Amoral, cunning, ruthless, and instructive, this piercing work distills three thousand years of the history of power in to forty-eight well explicated laws. As attention--grabbing in its design as it is in its content, this bold volume outlines the laws of power in their unvarnished essence, synthesizing the philosophies of Machiavelli, Sun-tzu, Carl von Clausewitz, and other great thinkers. Some laws teach the need for prudence ("Law 1: Never Outshine the Master"), the virtue of stealth ("Law 3: Conceal Your Intentions"), and many demand the total absence of mercy ("Law 15: Crush Your Enemy Totally"), but like it or not, all have applications in real life. Illustrated through the tactics of Queen Elizabeth I, Henry Kissinger, P. T. Barnum, and other famous figures who have wielded--or been victimized by--power, these laws will fascinate any reader interested in gaining, observing, or defending against ultimate control.',
    },
    subject_places: null,
    subject_people: null,
    subject_times: ["Ao longo de toda história"],
    subjects: [
      "Business",
      "Control (Psychology)",
      "Contrôle (Psychologie)",
      "Pouvoir (Morale)",
      "Nonfiction",
      "Power (Philosophy)",
      "Self-Improvement",
      "Conduct of life",
      "Contrãole (Psychologie",
      "Political Science",
      "Abridged Audio - Misc. Nonfiction",
      "Politics/International Relations",
      "History & Theory - General",
      "Political Science / History & Theory",
      "Audiobooks",
      "Political science & theory",
      "Psychology",
      "Contrôle (Psychologie.)",
      "Pouvoir (Morale.)",
      "BUSINESS & ECONOMICS",
      "Leadership",
      "Motivational",
      "SELF-HELP",
      "Personal Growth",
      "Success",
      "Macht",
      "Nutzung",
      "Gesellschaft",
      "Zwischenmenschliche Beziehung",
      "Power (Social sciences)",
      "Power (Psychology)",
      "Control (Philosophy)",
      "poder",
      "influência",
      "manipulação",
      "liderança",
      "ambição",
      "jogo",
      "persuasão",
      "Philosophy and ethics",
    ],
    publish_date: "1998",
    publishers: ["Penguin"],
    number_of_pages: null,
    isbn_10: null,
    isbn_13: null,
    languages: [{ key: "/languages/eng" }],
    physical_dimensions: null,
    ratings: {
      summary: {
        average: 4.0814332247557,
        count: 921,
        sortable: 3.998074664200514,
      },
      counts: { "1": 124, "2": 34, "3": 59, "4": 130, "5": 574 },
    },
    edition_key: "OL25418275M",
    cover_urls: [
      "https://covers.openlibrary.org/b/olid/OL24274306M-M.jpg",
      "https://covers.openlibrary.org/b/olid/OL25418275M-M.jpg",
    ],
    status: "read",
    review: "good",
    colors: { primary: "#B39230", secondary: "#CCA5A5" },
    spines: [
      {
        cacheKey: "OL1968368W-spine-placeholder",
        selected: false,
        originalImageHeight: 200,
        originalImageWidth: 60,
      },
      {
        cacheKey: "OL1968368W-spine-1744549932192",
        selected: true,
        originalImageHeight: 492,
        originalImageWidth: 149,
      },
    ],
  },
  {
    author_name: ["Brandon Sanderson"],
    cover_edition_key: "OL24345134M",
    first_publish_year: 2010,
    key: "OL15358691W",
    title: "The Way of Kings",
    editions: {
      numFound: 19,
      start: 0,
      numFoundExact: true,
      docs: [{ key: "/books/OL24383834M", title: "The Way of Kings" }],
    },
    cover_url: "https://covers.openlibrary.org/b/olid/OL24345134M-M.jpg",
    subtitle: null,
    author: "Brandon Sanderson",
    description:
      "Widely acclaimed for his work completing Robert Jordan’s Wheel of Time saga, Brandon Sanderson now begins a grand cycle of his own, one every bit as ambitious and immersive.\r\n\r\nRoshar is a world of stone and storms. Uncanny tempests of incredible power sweep across the rocky terrain so frequently that they have shaped ecology and civilization alike. Animals hide in shells, trees pull in branches, and grass retracts into the soilless ground. Cities are built only where the topography offers shelter.\r\n\r\nIt has been centuries since the fall of the ten consecrated orders known as the Knights Radiant, but their Shardblades and Shardplate remain: mystical swords and suits of armor that transform ordinary men into near-invincible warriors. Men trade kingdoms for Shardblades. Wars are fought for them, and won by them.\r\n\r\nOne such war rages on a ruined landscape called the Shattered Plains. There, Kaladin, who traded his medical apprenticeship for a spear, has been reduced to slavery. In a war that makes no sense, where ten armies fight separately against a single foe, he struggles to save his men and to fathom the leaders who consider them expendable.\r\n\r\nBrightlord Dalinar Kholin commands one of those other armies. Like his brother, the late king, he is fascinated by an ancient text called The Way of Kings. Troubled by overpowering visions of ancient times and the Knights Radiant, he has begun to doubt his own sanity.\r\n\r\nAcross the ocean, an untried young woman named Shallan seeks to train under the eminent scholar and notorious heretic Jasnah Kholin, Dalinar’s niece. Though she genuinely loves learning, Shallan’s motives are less than pure. As she plans a daring theft, her research for Jasnah hints at secrets of the Knights Radiant and the true cause of the war.\r\n\r\nThe result of more than ten years of planning, writing, and worldbuilding, The Way of Kings is but the opening movement of the Stormlight Archive, a bold masterpiece in the making.\r\n\r\nSpeak again the ancient oaths,\r\n\r\nLife before death.\r\nStrength before weakness.\r\nJourney before destination.\r\n\r\nand return to men the Shards they once bore.\r\n\r\nThe Knights Radiant must stand again.\r\n\r\n-From Cover Flap",
    subject_places: null,
    subject_people: null,
    subject_times: null,
    subjects: [
      "New York Times Bestseller",
      "Fantasy",
      "Epic Fantasy",
      "Imaginary places",
      "Kings and rulers",
      "Magic",
      "Imaginary wars and battles",
      "Manuscripts",
      "Slavery",
      "Fiction",
      "Fiction, fantasy, epic",
      "high fantasy",
      "nyt:hardcover-fiction=2010-09-19",
      "Fiction, fantasy, general",
      "American literature",
      "series:Stormlight Archive",
    ],
    publish_date: "2010",
    publishers: ["Tor"],
    number_of_pages: null,
    isbn_10: null,
    isbn_13: ["9780765326355"],
    languages: [{ key: "/languages/eng" }],
    physical_dimensions: null,
    ratings: {
      summary: {
        average: 4.556338028169014,
        count: 142,
        sortable: 4.386745743261276,
      },
      counts: { "1": 0, "2": 6, "3": 8, "4": 29, "5": 99 },
    },
    edition_key: "OL24383834M",
    cover_urls: [
      "https://covers.openlibrary.org/b/olid/OL24345134M-M.jpg",
      "https://covers.openlibrary.org/b/olid/OL24383834M-M.jpg",
    ],
    status: "finished",
    review: "good",
    colors: { primary: "#D6E9FF", secondary: "#FFCA60" },
    spines: [
      {
        cacheKey: "OL15358691W-spine-placeholder",
        selected: false,
        originalImageHeight: 200,
        originalImageWidth: 60,
      },
      {
        cacheKey: "OL15358691W-spine-1744555134742",
        selected: true,
        originalImageHeight: 2741,
        originalImageWidth: 723,
      },
    ],
  },
  {
    author_name: ["Timothy Ferriss"],
    cover_edition_key: "OL25426590M",
    first_publish_year: 2012,
    key: "OL16803605W",
    title: "The 4-Hour Chef",
    editions: {
      numFound: 1,
      start: 0,
      numFoundExact: true,
      docs: [{ key: "/books/OL25426590M", title: "The 4-Hour Chef" }],
    },
    cover_url: "https://covers.openlibrary.org/b/olid/OL25426590M-M.jpg",
    subtitle: null,
    author: "Timothy Ferriss",
    description: {
      type: "/type/text",
      value:
        'Building upon Timothy Ferriss\'s internationally successful "4-hour" franchise, "The 4-Hour Chef" transforms the way we cook, eat, and learn. You\'ll train inside the kitchen for everything outside the kitchen. Featuring recipes and cooking tricks from world-renowned chefs, and interspersed with the radically counterintuitive advice Ferriss\'s fans have come to expect, "The 4-Hour Chef" is a practical but unusual guide to mastering food and cooking, whether you are a seasoned pro or a blank-slate novice. This "cookbook for people who don\'t buy cookbooks" is a guide to mastering cooking and life. - Publisher.',
    },
    subject_places: null,
    subject_people: null,
    subject_times: null,
    subjects: [
      "Cooking",
      "nyt:hardcover-advice=2012-12-09",
      "New York Times bestseller",
      "Quick and easy cooking",
    ],
    publish_date: "2012",
    publishers: ["New Harvest, Hougton Mifflin Harcourt"],
    number_of_pages: 671,
    isbn_10: ["0547884591"],
    isbn_13: ["9780547884592"],
    languages: [{ key: "/languages/eng" }],
    physical_dimensions: "24 x  x  centimeters",
    ratings: {
      summary: { average: 3.4, count: 5, sortable: 2.468836543582764 },
      counts: { "1": 1, "2": 0, "3": 2, "4": 0, "5": 2 },
    },
    edition_key: "OL25426590M",
    cover_urls: [
      "https://covers.openlibrary.org/b/olid/OL25426590M-M.jpg",
      "https://covers.openlibrary.org/b/olid/OL25426590M-M.jpg",
    ],
    status: "finished",
    review: "good",
    colors: { primary: "#BDD537", secondary: "#839248" },
    spines: [
      {
        cacheKey: "OL16803605W-spine-placeholder",
        selected: false,
        originalImageHeight: 200,
        originalImageWidth: 60,
      },
      {
        cacheKey: "OL16803605W-spine-1744555763275",
        selected: true,
        originalImageHeight: 654,
        originalImageWidth: 171,
      },
    ],
  },
];
